name: uhc_lg_zoe
main: ch.kalunight.uhclg.ZoePluginMaster
authors: [KaluNitht]
version: "1.0"
api-version: "1.15"

commands:
 lgstart:
  description: Démarre la partie
  usage: /lgstart
 lgmodel:
  description: Définit un modèle pour l'enfant sauvage
  usage: /lgmodel nomModele
 lgliste:
  description: Liste tous les loups garous de la partie
  usage: /lgliste
 lgvoir:
  description: Révèle un rôle d'un joueur une fois pas jour, vous devez être voyante.
  usage: /lgvoir nomDuJoueur
 lgsauver:
  description: Sauve un joueur
  usage: /lgsauver nomDuJoueur
 lglove:
  description: Rend amoureux deux personnes
  usage: /lglove nomDuJoueur1 nomDuJoueur2
 lgdesc:
  description: Envoie la description du rôle du joueur
  usage: /lgdesc
 lgflairer:
  description: Révèle un joueur près de vous
  usage: /lgflairer nomDuJoueur