name: uhc_lg_zoe
main: ch.kalunight.uhclg.ZoePluginMaster
authors: [KaluNitht]
version: "1.0"
api-version: "1.15"

commands:
 lgstart:
  description: Démarre la partie
  usage: /lgstart
 lgmodel:
  description: Définit un modèle pour l'enfant sauvage
  usage: /lgmodel nomModele